# args for AI algorithms, see README for info
[AI]
# if anomaly detection is supervised (false) or unsupervised (true)
fitPredict = false

[anomaly]
contamination = 0.25
max_samples= "auto"


[cluster]
eps = 7
min_samples = 10