# args for AI algorithms, see README for info
[AI]
# if anomaly detection is supervised (false) or unsupervised (true)
fitPredict = false

[anomaly]

# contamination = 0.25
# max_samples= "auto"

n_estimators=50
max_samples= 20
max_features=2
contamination = 0.25
bootstrap=1
random_state=0
warm_start=0

[cluster]
eps = 7
min_samples = 10