# args for AI algorithms, see README for info
[AI]
# if anomaly detection is supervised (false) or unsupervised (true)
fitPredict = false

[anomaly]

contamination = 0.4
max_samples= "auto"

# n_estimators=100
# max_samples= 10
# max_features=2
# contamination = 0.25
# bootstrap=0
# random_state=1
# warm_start=0 

[cluster]
eps = 7
min_samples = 10