# config.toml
version = 1
[handlers.infofile]
class= "logging.handlers.RotatingFileHandler"
level= "INFO" # to catch info AND errors into this file
formatter= "simple"
filename="./logs/info.log"
maxBytes= 10485760
backupCount= 5
encoding= "utf8"

[handlers.errorfile]
class= "logging.handlers.RotatingFileHandler"
level= "ERROR" # to catch errors into this file
formatter= "simple"
filename="./logs/debug.log"
maxBytes= 10485760
backupCount= 5
encoding= "utf8"

[formatters.simple]
format= '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
datefmt= '%Y-%m-%d %H:%M:%S'

[root]
handlers=['infofile', 'errorfile']
level='INFO' # to catch everything

